# Generated by Django 2.0.5 on 2018-09-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=150),
        ),
    ]
