# Generated by Django 2.0.5 on 2018-09-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0005_auto_20180924_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=models.CharField(default=' - Sin caracteristicas -', max_length=150),
        ),
    ]
